import { Category, MoodType } from '@/types';

export const MOODS: { value: MoodType; emoji: string; description: string }[] = [
  { value: 'Playful', emoji: '🎨', description: 'Keep it fun and creative' },
  { value: 'Serious', emoji: '🎯', description: 'Goal-oriented and focused' },
  { value: 'Chaos Mode', emoji: '🌪️', description: 'Embrace the unpredictable' },
  { value: 'Overachiever', emoji: '⭐', description: 'All-in, maximum effort' },
  { value: 'Balanced', emoji: '⚖️', description: 'Sustainable and steady' },
];

export const CATEGORIES: Category[] = [
  {
    slug: 'extracurriculars',
    title: 'Extracurricular',
    description: 'Hobbies, creative pursuits, fun activities. Or think about what you used to love doing when you were younger.',
    icon: '🎭',
  },
  {
    slug: 'leadership-roles',
    title: 'Leadership Role',
    description: 'Ways to lead, organize, or mentor others',
    icon: '👥',
  },
  {
    slug: 'career-growth',
    title: 'Career Growth',
    description: 'Professional development and goals',
    icon: '💼',
  },
  {
    slug: 'volunteer-causes',
    title: 'Volunteer Cause',
    description: 'Ways to give back to your community',
    icon: '❤️',
  },
  {
    slug: 'skill-development',
    title: 'Skill Development',
    description: 'New skills or knowledge to acquire',
    icon: '📚',
  },
  {
    slug: 'lifestyle',
    title: 'Lifestyle',
    description: 'Daily habits and wellness practices',
    icon: '🌱',
  },
];

export const INPUT_SUGGESTIONS: Record<string, string[]> = {
  'extracurriculars': [
  "Pottery",
  "Painting",
  "Drawing",
  "Sketching",
  "Watercolor",
  "Collage making",
  "Embroidery",
  "Knitting",
  "Crocheting",
  "Jewelry making",
  "Scrapbooking",
  "Creative writing",
  "Poetry nights",
  "Photography",
  "Filmmaking",
  "Vlogging",
  "Digital illustration",
  "Graphic design",
  "Animation basics",
  "Dance - hip-hop",
  "Dance - ballet",
  "Dance - salsa",
  "Dance - contemporary",
  "Acting",
  "Improv",
  "Stand-up comedy",
  "Piano",
  "Guitar",
  "Music production",
  "DJing",
  "Choir",
  "Voice lessons",
  "Pilates",
  "Yoga",
  "Bikram yoga",
  "Strength training",
  "Barre",
  "Rock climbing",
  "Hiking club",
  "Running club",
  "Recreational soccer",
  "Basketball",
  "Swimming",
  "Cycling",
  "Inline skating",
  "Dance cardio",
  "Pole fitness",
  "Martial arts",
  "Tennis",
  "Pickleball",
  "Boxing",
  "Cooking class",
  "Baking",
  "Mixology",
  "Candle making",
  "Perfume blending",
  "Sewing",
  "Fashion design",
  "Woodworking",
  "DIY furniture projects",
  "Calligraphy",
  "Coding",
  "Learning Spanish",
  "Learning French",
  "Learning Japanese",
  "Public speaking",
  "Chess",
  "Book club",
  "Debate group",
  "Philosophy circle",
  "Film critique club",
  "Foreign film nights",
  "Podcast club",
  "Community garden",
  "Gardening",
  "Houseplant club",
  "Nature walks",
  "Foraging",
  "Birdwatching",
  "Weekend camping",
  "Kayaking",
  "Paddle boarding",
  "Landscape photography",
  "Urban exploration",
  "Natural wine club",
  "Wine tasting group",
  "Dinner club",
  "Potluck club",
  "Game nights",
  "Co-working club",
  "Local meetups",
  "Organizing creative gatherings",
  "Volunteering",
  "Youth mentorship",
  "Animal shelter socials",
  "Neighborhood cleanup",
  "Roller skating",
  "Sticker collecting",
  "Beading",
  "Fan fiction writing",
  "Scrapbook journaling",
  "Puzzle nights",
  "Adult coloring books",
  "LEGO builds",
  "Baking/decorating",
  "Skateboarding",
  "Thrifting excursions",
  "Silent discos",
  "Kirtan or sound baths",
  "Car karaoke drives"
],
  'leadership-roles': [
  "Host a monthly meetup",
  "Lead a book club",
  "Start a community group",
  "Organize a volunteer event",
  "Mentor a younger professional",
  "Lead a coworking circle",
  "Start a creative collective",
  "Lead a fitness or walking group",
  "Host a weekly running meet",
  "Organize a weekend hiking group",
  "Host dinners or potlucks",
  "Run a workshop or skill-share",
  "Teach a class or intro lesson",
  "Facilitate a mastermind group",
  "Lead a team-building exercise",
  "Be a peer mentor at work",
  "Lead a project at work",
  "Head a workplace committee",
  "Start a networking group",
  "Organize a local career panel",
  "Host a speaker series",
  "Create a community newsletter",
  "Run an online group or Discord community",
  "Moderate a group chat or online forum",
  "Organize a reading series",
  "Lead a meditation circle",
  "Host a breathwork or mindfulness class",
  "Start a women's leadership circle",
  "Start a “learn together” accountability club",
  "Coach or tutor students",
  "Lead a youth mentorship group",
  "Coach a youth sports team",
  "Organize a clothing drive",
  "Plan a food donation effort",
  "Coordinate community cleanups",
  "Organize a neighborhood improvement group",
  "Start a mutual aid micro-group",
  "Organize a charity fundraiser",
  "Host a local art night",
  "Start a rotating creative salon",
  "Plan community social events",
  "Host a film discussion night",
  "Lead a writer's group",
  "Lead a photography walk",
  "Run a creative challenge",
  "Lead a hackathon or design sprint",
  "Be a TA or class assistant",
  "Be a workshop assistant",
  "Organize a peer accountability group",
  "Start a small incubator/idea lab",
  "Lead a local advocacy effort",
  "Organize a political action meeting",
  "Start a social justice discussion group",
  "Plan educational panels",
  "Lead a volunteer team shift",
  "Coordinate a mentorship pairing program",
  "Start a tech meetup",
  "Run a book swap or media swap event",
  "Lead a sustainable living group",
  "Start a gardening co-op",
  "Organize a community market or exchange",
  "Host a themed monthly gathering",
  "Start a neighborhood watch + wellness check group",
  "Lead a public speaking practice club",
  "Start a Toastmasters-style circle",
  "Plan travel groups or weekend day trips",
  "Host a local culture discovery group",
  "Organize nature restoration meetups",
  "Start a bike-to-work crew",
  "Lead a social hiking challenge",
  "Organize an art therapy night",
  "Lead a journaling circle",
  "Coach peers on skills you know",
  "Host a networking brunch",
  "Start a small advisory board for friends",
  "Become a community liaison for a nonprofit",
  "Serve as a nonprofit board member",
  "Join or lead a school alumni committee",
  "Run community surveys or research efforts",
  "Become a community ambassador for an org",
  "Lead supply drives for shelters",
  "Create a mini educational curriculum",
  "Host weekly co-study sessions",
  "Plan structured monthly challenges",
  "Lead a mentorship circle",
  "Create and run a digital learning cohort",
  "Start a BIPOC professional circle",
  "Plan small local conferences",
  "Organize a coworking retreat",
  "Host group workouts in the park",
  "Lead a climate action team",
  "Organize parent-and-kids community nights",
  "Run a conflict resolution or communication circle",
  "Start a civic engagement group",
  "Organize small community repairs or renovations",
  "Lead a neighborhood history walk",
  "Host a Sunday reflection or intention-setting group"
]
,
  'career-growth': [
  "Build a personal portfolio",
  "Redesign my personal website",
  "Update my resume",
  "Refresh my LinkedIn profile",
  "Create a professional elevator pitch",
  "Learn a new programming language",
  "Learn TypeScript",
  "Learn React or Next.js",
  "Learn AI tools professionally",
  "Take a machine learning fundamentals course",
  "Take a data analytics course",
  "Learn SQL",
  "Learn UX/UI design",
  "Learn product design",
  "Learn product management foundations",
  "Ship a side project",
  "Build and launch a small app",
  "Create a product case study",
  "Build an online portfolio of work",
  "Practice coding challenges weekly",
  "Contribute to open source",
  "Start a newsletter about my field",
  "Write weekly industry posts",
  "Write an in-depth blog article",
  "Start a podcast or video series",
  "Speak at a meetup",
  "Present at a conference",
  "Host a workshop",
  "Host a webinar",
  "Join a professional organization",
  "Attend more industry events",
  "Join a mastermind group",
  "Start a mastermind group",
  "Seek out a mentor",
  "Become a mentor",
  "Shadow someone in a dream role",
  "Ask for more responsibility at work",
  "Take the lead on a work project",
  "Start a documentation habit",
  "Improve public speaking",
  "Practice communication skills",
  "Improve negotiation skills",
  "Learn leadership skills",
  "Learn conflict resolution",
  "Take a career development course",
  "Earn a certification",
  "Get Agile or Scrum-certified",
  "Take a project management course",
  "Study business strategy",
  "Learn financial literacy for career growth",
  "Create a personal development plan",
  "Create a 6-month career roadmap",
  "Build a project-based learning plan",
  "Create a system for networking",
  "Network weekly (1–2 new people)",
  "Reconnect with old contacts",
  "Join an online industry community",
  "Start a personal knowledge management system",
  "Improve time management",
  "Learn deep work techniques",
  "Build a strong weekly workflow",
  "Improve my writing for clarity",
  "Build a personal brand identity",
  "Create a visual brand kit",
  "Start consulting or freelancing",
  "Build a freelance portfolio",
  "Learn pricing and client management",
  "Launch a digital product",
  "Create & sell templates or tools",
  "Start a small online business",
  "Explore a new career direction",
  "Take a career clarity assessment",
  "Find a part-time or contract role",
  "Start interviewing again",
  "Prepare for technical interviews",
  "Learn how to negotiate job offers",
  "Study successful people in my field",
  "Create case studies from past work",
  "Start a research project",
  "Join a cohort-based course",
  "Develop better presentation skills",
  "Learn storytelling for business",
  "Take a design thinking course",
  "Improve my portfolio storytelling",
  "Get great at slide design",
  "Automate repetitive parts of my job",
  "Learn workplace tools (Notion, Figma, Airtable)",
  "Build my own productivity system",
  "Start a productivity accountability group",
  "Track my career wins weekly",
  "Ask for a raise or promotion",
  "Apply for stretch roles",
  "Design a dream role and reverse-engineer it",
  "Build cross-functional skills",
  "Learn how to manage people",
  "Start managing someone informally",
  "Practice giving feedback",
  "Develop emotional intelligence",
  "Raise my visibility at work"
]
,
  'volunteer-causes': [
  "Support children and youth",
  "Tutor students in reading or math",
  "Mentor teens or young adults",
  "Assist in after-school programs",
  "Volunteer at local schools",
  "Support special education programs",
  "Help at youth sports leagues",
  "Volunteer with Big Brothers Big Sisters",
  "Work with children's hospitals",
  "Help with childcare at community events",
  "Support homelessness prevention",
  "Help distribute meals at food banks",
  "Sort donations at food pantries",
  "Deliver meals to seniors or homebound adults",
  "Work with shelters and transitional housing",
  "Volunteer at warming shelters",
  "Support domestic violence survivors",
  "Volunteer at women’s shelters",
  "Assist sexual assault survivor support orgs",
  "Support refugees and asylum seekers",
  "Help immigrant families with paperwork",
  "Teach English or language skills",
  "Support LGBTQ+ youth organizations",
  "Support elder care communities",
  "Visit seniors in assisted living",
  "Run activities for older adults",
  "Support mental health hotlines",
  "Support crisis text lines",
  "Help with peer emotional support groups",
  "Volunteer for suicide prevention efforts",
  "Support animal shelters",
  "Walk shelter dogs",
  "Foster animals short-term",
  "Assist in animal rescue transport",
  "Volunteer at wildlife rehabilitation centers",
  "Protect local ecosystems",
  "Park and trail conservation",
  "Tree planting and habitat restoration",
  "Beach and river cleanups",
  "Support community gardens",
  "Assist urban farming initiatives",
  "Help maintain neighborhood green spaces",
  "Support food justice movements",
  "Distribute produce at mobile pantries",
  "Support local farms and markets",
  "Help at farmers market booths",
  "Support arts and culture nonprofits",
  "Volunteer at local theaters",
  "Help at museums and galleries",
  "Assist with cultural festival events",
  "Support library volunteer programs",
  "Teach literacy or adult education",
  "Help with computer literacy classes",
  "Support job readiness training",
  "Resume and interview coaching",
  "Teach financial literacy workshops",
  "Volunteer with career mentorship programs",
  "Help build affordable housing",
  "Support Habitat for Humanity",
  "Join community repair or build days",
  "Volunteer for disaster relief",
  "Assemble emergency kits",
  "Support Red Cross events",
  "Organize neighborhood resilience networks",
  "Participate in community cleanups",
  "Organize clothing drives",
  "Distribute hygiene kits",
  "Support period poverty organizations",
  "Help at community meal programs",
  "Support community fridges",
  "Volunteer in local mutual aid groups",
  "Assist with local political organizing",
  "Support civic engagement drives",
  "Register voters",
  "Volunteer at polling locations",
  "Support environmental justice orgs",
  "Assist with anti-racism community workshops",
  "Support prison education programs",
  "Volunteer for restorative justice circles",
  "Support foster care and adoption orgs",
  "Host supply drives for kids in foster care",
  "Assist community tech centers",
  "Teach art or creativity classes",
  "Help run youth leadership workshops",
  "Support community mental health events",
  "Volunteer with health clinics",
  "Assist at blood donation drives",
  "Support community wellness initiatives",
  "Volunteer with crisis response teams",
  "Support local hospitals",
  "Help organize charity walks or races",
  "Support small local nonprofits",
  "Help build nonprofit operations systems",
  "Event support for community fundraisers",
  "Volunteer at nature centers",
  "Help maintain historical landmarks",
  "Support local advocacy campaigns"
],
  'skill-development': [
  "Learn a new language",
  "Learn Spanish",
  "Learn French",
  "Learn Japanese",
  "Learn Korean",
  "Learn Italian",
  "Learn coding",
  "Learn TypeScript",
  "Learn JavaScript",
  "Learn Python",
  "Learn React",
  "Learn Next.js",
  "Learn SQL",
  "Learn data analytics",
  "Learn machine learning fundamentals",
  "Learn AI tools and workflows",
  "Learn prompt engineering",
  "Learn UX/UI design",
  "Learn product design",
  "Learn graphic design",
  "Learn digital illustration",
  "Learn animation basics",
  "Learn 3D modeling",
  "Learn photography",
  "Learn videography",
  "Learn video editing",
  "Learn color grading",
  "Learn podcast editing",
  "Improve writing skills",
  "Learn storytelling fundamentals",
  "Learn copywriting",
  "Learn creative writing",
  "Learn scriptwriting",
  "Learn journalistic writing",
  "Learn public speaking",
  "Learn presentation design",
  "Learn how to run workshops",
  "Learn facilitation skills",
  "Learn leadership skills",
  "Learn management skills",
  "Learn conflict resolution",
  "Build emotional intelligence",
  "Learn negotiation",
  "Learn persuasion",
  "Learn people skills",
  "Learn networking strategies",
  "Learn career planning techniques",
  "Learn business strategy fundamentals",
  "Learn entrepreneurship basics",
  "Learn how to start a small business",
  "Learn marketing fundamentals",
  "Learn brand design",
  "Learn social media strategy",
  "Learn SEO and analytics",
  "Learn financial literacy",
  "Learn investing basics",
  "Learn budgeting systems",
  "Learn tax literacy",
  "Learn productivity systems",
  "Learn time management",
  "Learn how to build a personal OS",
  "Learn Notion",
  "Learn Figma",
  "Learn Airtable",
  "Learn Canva",
  "Learn email marketing",
  "Learn sales and client management",
  "Learn consulting skills",
  "Learn project management",
  "Get Agile or Scrum training",
  "Learn risk management",
  "Learn systems thinking",
  "Learn research skills",
  "Learn how to run interviews",
  "Learn data visualization",
  "Learn organizational psychology basics",
  "Learn cooking fundamentals",
  "Learn baking",
  "Learn mixology",
  "Learn sewing",
  "Learn knitting or crochet",
  "Learn fashion design basics",
  "Learn woodworking",
  "Learn calligraphy",
  "Learn pottery",
  "Learn ceramics wheel throwing",
  "Learn floral arranging",
  "Learn gardening",
  "Learn foraging",
  "Learn meditation",
  "Learn breathwork",
  "Learn mindfulness practices",
  "Learn first aid and CPR",
  "Learn home repair basics",
  "Learn car maintenance",
  "Learn travel hacking",
  "Learn hosting/entertaining skills",
  "Learn interior design fundamentals",
  "Learn decluttering/organizing techniques"
],
  'lifestyle': [
  "Morning stretch routine",
  "Daily 10-minute meditation",
  "Evening mindfulness ritual",
  "Daily journaling",
  "Daily gratitude list",
  "Drink more water",
  "Consistent sleep schedule",
  "Go on daily walks",
  "Daily time outdoors",
  "No-phone mornings",
  "No-phone nights",
  "Daily reading habit",
  "Daily affirmations",
  "Weekly meal prep",
  "Daily skincare routine",
  "Weekly digital declutter",
  "Weekly home reset",
  "Daily home tidying",
  "Weekly self-date",
  "Weekly creativity time",
  "Daily step goal",
  "Daily sunlight exposure",
  "Stable morning routine",
  "Smoother bedtime routine",
  "Strength training 2–3x/week",
  "Yoga or mat Pilates",
  "Weekly therapy or mental health check-in",
  "Mindful eating",
  "Weekly money check-in",
  "No sugar weekdays",
  "Less caffeine",
  "Daily stretching for flexibility",
  "Hydration routine",
  "Daily language practice",
  "Daily learning habit",
  "Weekly social connection",
  "Weekly community activity",
  "Limit screen time",
  "Weekly house project",
  "Daily creative play"
],
};
